### ISSUE TITLE
Redis Adapter issue when host is url

### ISSUE THREAD

**Issue by jackbit** [translationexchange/tml-ruby#2]
I found issue when redis is url like this: redis://lorem.ipsum.dolor.cit.net:6379
your adapter will be redis:6379 which is incorrect, and then no way to include username and password.

https://github.com/translationexchange/tml-ruby/blob/master/lib/tml/cache_adapters/redis.rb#L41-L48

new approaches:

```
# intializers
config.cache = {
    :enabled  => true,
    :adapter  => 'redis',
    :adapter_config  => {
        host: ' localhost',
        port: '6379',
        namespace: '',
        username: '',
        password: '',
    },
    :version  => 5,
    :timeout  => 3600
  }


# lib/tml/cache_adapters/redis.rb
class Tml::CacheAdapters::Redis < Tml::Cache

  def initialize
    config = Tml.config.cache
    config[:adapter_config] ||= {host: 'localhost', port: '6379'}
    @cache = ::Redis.new(config[:adapter_config])
  end
```

**Comment by berk** [comment]
Good idea. I've added the adapter_config as a separate option. I need to support the other options for backwards compatibility for now. I will update the docs to use your suggestion in the future.

https://github.com/translationexchange/tml-ruby/blob/master/lib/tml/cache_adapters/redis.rb#L41-L54
